### GETTING STARTED

In [26]:
import numpy as np

In [27]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [29]:
arr = np.array([1,12,3,2,2], ndmin =26 )
print(arr.ndim)

26


In [30]:
firstarr = np.array([1,2,44,5,33,32])

# selecting the third column
print([2])
secondarr = np.array([[1,23,42,32],[23,3,43,53]])

# selecting the second row second column
print([1,1])
thirdarr = np.array([[[32,23,2],[32,234,3]],[[23,234,23],[53,64,6]]])

# selecting the first row second column 3rd ... 
print([0,1,2])

[2]
[1, 1]
[0, 1, 2]


In [31]:
### slicing 
#1D
# [a:b:c] a is the start index b is the end index and c is the step 
#2D
#[from element,return ]

# since this is a 2d array we are printing both rows from 2nd to 5th column 
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])




[[2 3 4]
 [7 8 9]]


In [32]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

print(arr.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64


In [33]:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
# .dtype to show the type of the array variables , type() to show the type of array itself 
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [34]:
# to convert an array we use astype methode 
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [35]:
arr = np.array([1,2,3,3,4,8,5])
# copy() copies the original array into a new variable 
arrcopy = arr.copy()
# view () creates a shortcut of the original array 
arrshort = arr.view()



In [36]:
# we reshape from 1D to 2D
# we use .reshape()
arr = np.array([1,2,3,3,4,8,5,2,9,1,5,2])
# reshape to 4 rows 3 colums
newarr = arr.reshape(4,3)
print(newarr)

[[1 2 3]
 [3 4 8]
 [5 2 9]
 [1 5 2]]


In [ ]:
# to reshape from 2D 3D 
arr = np.array([1,2,3,3,4,8,5,2,9,1,5,2])
newarr = arr.reshape(3,4)
arr3d = arr.reshape(2,2,3)
print(newarr)
print(arr3d)

